version: '3.4'

services:
  bankfrontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - bank

networks:
  bank:
    driver: bridge