version: '3.4'

services:
  react-app:
    build:
      context: ./bank-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - bank

  bank-api:
    build:
      context: ./Bank-RestAPI
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - bank
  transaction-api:
    build:
      context: ./transaction
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    networks:
      - bank  



networks:
  bank:
    driver: bridge