name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: dap2004/example
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.MI_USUARIO_DE_DOCKER }}
          password: ${{ secrets.MI_SUPER_CLAVE }}